modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://minecraft.curseforge.com/projects/coffee-spawner/issues"
license="All rights reserved"

[[mods]] #mandatory
modId="coffeespawner"
version="1.16.3-7.0.0"
displayName="Coffee Spawner"
displayURL="https://minecraft.curseforge.com/projects/coffee-spawner"
authors="Ruuubi"
description='''Adds a coffee machine which spawns a drinkable coffee every morning'''

[[dependencies.coffeespawner]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.14,)"
    ordering="NONE"
	side="BOTH"