modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://minecraft.curseforge.com/projects/coffee-spawner/issues"

[[mods]] #mandatory
modId="coffeespawner"
version="1.14.4-5.0.0"
displayName="Coffee Spawner"
# updateJSONURL=""
displayURL="https://minecraft.curseforge.com/projects/coffee-spawner"
# logoFile="logo.png"
# credits=""
authors="Ruuubi"
description='''Adds a coffee machine which spawns a drinkable coffee every morning'''

[[dependencies.coffeespawner]]
    modId="forge"
    mandatory=true
    versionRange="[28.0.11,)"
    ordering="NONE"
	side="BOTH"