modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL="https://minecraft.curseforge.com/projects/coffee-spawner/issues"

[[mods]] #mandatory
modId="coffeespawner"
version="1.15.1-6.0.0"
displayName="Coffee Spawner"
# updateJSONURL=""
displayURL="https://minecraft.curseforge.com/projects/coffee-spawner"
# logoFile="logo.png"
# credits=""
authors="Ruuubi"
description='''Adds a coffee machine which spawns a drinkable coffee every morning'''

[[dependencies.coffeespawner]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.41,)"
    ordering="NONE"
	side="BOTH"